PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT * WHERE {

	OPTIONAL {
		<__URI__> wdt:P577 ?releaseDate .
	}

	OPTIONAL {
		<__URI__> wdt:P57 ?directorUri .
		?directorUri rdfs:label ?director
		FILTER (lang(?director) = "en")
	}

	OPTIONAL {
		<__URI__> wdt:P1657 _:rating .
		_:rating rdfs:label ?rating
		FILTER (lang(?rating) = "en")
	}

	OPTIONAL {
		<__URI__> wdt:P166 _:award .
		_:award rdfs:label ?award
		FILTER (lang(?award) = "en")
	}
}
