PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wsi: <http://whostarredin.com/data/>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
	?actor rdfs:label ?label ;
           wsi:movie	?movie ;
           schema:about ?cleanedWikipediaLink
}

WHERE {
  	?movie wdt:P161 ?actor .

  	?actor	rdfs:label ?label .

    ?cleanedWikipediaLink schema:about ?actor

    FILTER(LANG(?label) = "en" || LANG(?label) = "" )
}
