PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT * WHERE {
	?film wdt:P31 wd:Q11424 ; rdfs:label ?label
  FILTER (lang(?label) = "en")
}
# Add a limit  & page through results; overlap pages.
# E.g.:
# First run -
# LIMIT 50000
# Second run -
# LIMIT 95000
# OFFSET 45000
# Third run - 
# LIMIT 12000
# OFFSET 90000
# etc...
